/* Palette generated by Material Palette - materialpalette.com/cyan/lime */

export const DARK_PRIMARY_COLOR = '#0097A7'
export const DEFAULT_PRIMARY_COLOR = '#00BCD4'
export const LIGHT_PRIMARY_COLOR = '#B2EBF2'
export const TEXT_PRIMARY_COLOR = '#FFFFFF'
export const ACCENT_COLOR = '#CDDC39'
export const PRIMARY_TEXT_COLOR = '#212121'
export const SECONDARY_TEXT_COLOR = '#757575'
export const DIVIDER_COLOR = '#BDBDBD'
export const DRAWER_WIDTH = 320
export const HEADER_HEIGHT = 64
export const ERROR_COLOR = '#ff1744'
export const MAX_WIDTH = 900
