/* Palette generated by Material Palette - materialpalette.com/cyan/lime */

.dark-primary-color    { background: #0097A7; }
.default-primary-color { background: #00BCD4; }
.light-primary-color   { background: #B2EBF2; }
.text-primary-color    { color: #FFFFFF; }
.accent-color          { background: #CDDC39; }
.primary-text-color    { color: #212121; }
.secondary-text-color  { color: #757575; }
.divider-color         { border-color: #BDBDBD; }



// /* Palette generated by Material Palette - materialpalette.com/indigo/red */
//
// export const DARK_PRIMARY_COLOR = '#303F9F'
// export const DEFAULT_PRIMARY_COLOR = '#3F51B5'
// export const LIGHT_PRIMARY_COLOR = '#C5CAE9'
// export const TEXT_PRIMARY_COLOR = '#FFFFFF'
// export const ACCENT_COLOR = '#FF5252'
// export const PRIMARY_TEXT_COLOR = '#212121'
// export const SECONDARY_TEXT_COLOR = '#757575'
// export const DIVIDER_COLOR = '#BDBDBD'
