// NOTIFICATION
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION'
export const OPEN_DRAWER = 'OPEN_DRAWER'
export const CLOSE_DRAWER = 'CLOSE_DRAWER'
export const GOTO = 'GOTO'
export const SET_ON_EPISODE_PAGE = 'SET_ON_EPISODE_PAGE'
export const CLEAR_ON_EPISODE_PAGE = 'CLEAR_ON_EPISODE_PAGE'
export const ALERT = 'ALERT'
