// NOTIFICATION
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION'
export const OPEN_SIDEBAR = 'OPEN_SIDEBAR'
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR'
export const GOTO = 'GOTO'
export const SET_ON_EPISODE_PAGE = 'SET_ON_EPISODE_PAGE'
export const CLEAR_ON_EPISODE_PAGE = 'CLEAR_ON_EPISODE_PAGE'
