export const FETCH_COURSES_STARTED = 'FETCH_COURSES_STARTED'
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS'

export const FETCH_COURSE_STARTED = 'FETCH_COURSE_STARTED'
export const FETCH_CURRENT_COURSE_SUCCESS = 'FETCH_CURRENT_COURSE_SUCCESS'

export const FETCH_EPISODE_STARTED = 'FETCH_EPISODE_STARTED'
export const FETCH_EPISODE_SUCCESS = 'FETCH_EPISODE_SUCCESS'
